In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import time
from scipy.stats import linregress
from pathlib import Path

pop_2017 = Path("../tx_pop_zip_2017.csv")
pop_2018 = Path("../tx_pop_zip_2018.csv")
pop_2019 = Path("../tx_pop_zip_2019.csv")
pop_2020 = Path("../tx_pop_zip_2020.csv")
pop_2021 = Path("../tx_pop_zip_2021.csv")
pop_2022 = Path("../tx_pop_zip_2022.csv")
zip_cities = Path("../uszips.csv")

columns_delete = ['GEO_ID', 'B01003_001M', 'Unnamed: 4']
data_2017 = pd.DataFrame(pd.read_csv(pop_2017)).drop(columns = columns_delete)
data_2018 = pd.DataFrame(pd.read_csv(pop_2018)).drop(columns = columns_delete)
data_2019 = pd.DataFrame(pd.read_csv(pop_2019)).drop(columns = columns_delete)
data_2020 = pd.DataFrame(pd.read_csv(pop_2020)).drop(columns = columns_delete)
data_2021 = pd.DataFrame(pd.read_csv(pop_2021)).drop(columns = columns_delete)
data_2022 = pd.DataFrame(pd.read_csv(pop_2022)).drop(columns = columns_delete)
city_zip = pd.DataFrame(pd.read_csv(zip_cities, delimiter = ","))

first_merge = pd.merge(data_2017, data_2018, on = 'NAME', how = 'outer')
first_merge = first_merge.rename(columns = {"B01003_001E_x": "A", "B01003_001E_y": "B"})
second_merge = pd.merge(first_merge, data_2019, on = 'NAME', how = 'outer')
second_merge = second_merge.rename(columns = {"B01003_001E": "C"})
third_merge = pd.merge(second_merge, data_2020, on = 'NAME', how = 'outer')
third_merge = third_merge.rename(columns = {"B01003_001E": "D"})
fourth_merge = pd.merge(third_merge, data_2021, on = 'NAME', how = 'outer')
fourth_merge = fourth_merge.rename(columns = {"B01003_001E": "E"})
population_growth_df = pd.merge(fourth_merge, data_2022, on = 'NAME', how = 'outer')
population_growth_df = population_growth_df.rename(columns = {"B01003_001E": "F"})
pd.reset_option('display.max_rows', None)

population_growth_df.loc[0, 'NAME'] = "Zip Code"
population_growth_df.loc[0, 'A'] = "2017"
population_growth_df.loc[0, 'B'] = "2018"
population_growth_df.loc[0, 'C'] = "2019"
population_growth_df.loc[0, 'D'] = "2020"
population_growth_df.loc[0, 'E'] = "2021"
population_growth_df.loc[0, 'F'] = "2022"

population_growth_df.columns = population_growth_df.iloc[0]
population_growth_df = population_growth_df[1:]
population_growth_df["Zip Code"] = population_growth_df["Zip Code"].str.replace("ZCTA5 ", '')
population_growth_df = population_growth_df.set_index('Zip Code')
population_growth_df = population_growth_df.sort_index()
population_growth_df = population_growth_df.dropna(how="any")

texas_min_zip = 75000
texas_max_zip = 79999

population_growth_df.index = population_growth_df.index.astype(int)
mask = (population_growth_df.index >= texas_min_zip) & (population_growth_df.index <= texas_max_zip)
population_growth_df = population_growth_df[mask]

population_growth_df

0           2017    2018    2019    2020    2021    2022
Zip Code
75001      14617   15000   14992   15418   16287   16633
75002      69688   70597   71253   73916   71102   72679
75006      50788   51136   51642   52231   48104   48062
75007      53744   54701   55500   57513   54448   54498
75009      10557   11941   14089   15348   24737   28109
...          ...     ...     ...     ...     ...     ...
79932      28345   28682   28243   28893   28594   29269
79934      25846   26289   26445   26360   26916   26620
79935      18166   17434   17850   18546   19073   18815
79936     111918  112355  111620  108668  107579  107512
79938      77487   80143   84237   83326   91575   95452

[1925 rows x 6 columns]

In [2]:
city_zip["zip"] = city_zip["zip"].astype(str)
city_zip

,zip,lat,lng,city,state_id,state_name,zcta,parent_zcta,population,density,county_fips,county_name,county_weights,county_names_all,county_fips_all,imprecise,military,timezone
0,601,18.18027,-66.75266,Adjuntas,PR,Puerto Rico,True,NaN,17126.0,102.6,72001,Adjuntas,"{""72001"": 98.73, ""72141"": 1.27}",Adjuntas|Utuado,72001|72141,False,False,America/Puerto_Rico
1,602,18.36075,-67.17541,Aguada,PR,Puerto Rico,True,NaN,37895.0,482.5,72003,Aguada,"{""72003"": 100}",Aguada,72003,False,False,America/Puerto_Rico
2,603,18.45744,-67.12225,Aguadilla,PR,Puerto Rico,True,NaN,49136.0,552.4,72005,Aguadilla,"{""72005"": 99.76, ""72099"": 0.24}",Aguadilla|Moca,72005|72099,False,False,America/Puerto_Rico
3,606,18.16585,-66.93716,Maricao,PR,Puerto Rico,True,NaN,5751.0,50.1,72093,Maricao,"{""72093"": 82.27, ""72153"": 11.66, ""72121"": 6.06}",Maricao|Yauco|Sabana Grande,72093|72153|72121,False,False,America/Puerto_Rico
4,610,18.29110,-67.12243,Anasco,PR,Puerto Rico,True,NaN,26153.0,272.1,72011,AÃ±asco,"{""72011"": 96.7, ""72099"": 2.81, ""72083"": 0.37, ...",AÃ±asco|Moca|Las MarÃ­as|Aguada,72011|72099|72083|72003,False,False,America/Puerto_Rico
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33783,99923,55.98043,-130.03803,Hyder,AK,Alaska,True,NaN,13.0,0.3,2198,Prince of Wales-Hyder,"{""02198"": 100}",Prince of Wales-Hyder,2198,False,False,America/Sitka
33784,99925,55.55398,-132.96276,Klawock,AK,Alaska,True,NaN,917.0,6.6,2198,Prince of Wales-Hyder,"{""02198"": 100}",Prince of Wales-Hyder,2198,False,False,America/Sitka
33785,99926,55.12617,-131.48928,Metlakatla,AK,Alaska,True,NaN,1445.0,4.2,2198,Prince of Wales-Hyder,"{""02198"": 100}",Prince of Wales-Hyder,2198,False,False,America/Metlakatla
33786,99927,56.33305,-133.60044,Point Baker,AK,Alaska,True,NaN,11.0,0.9,2198,Prince of Wales-Hyder,"{""02198"": 100}",Prince of Wales-Hyder,2198,False,False,America/Sitka
33787,99929,56.36089,-132.00635,Wrangell,AK,Alaska,True,NaN,2161.0,0.3,2275,Wrangell,"{""02275"": 100}",Wrangell,2275,False,False,America/Sitka

In [3]:
texas_mask = city_zip["state_id"] == "TX"
tx_city_zip = city_zip[texas_mask]
tx_city_zip = tx_city_zip.set_index("zip")
tx_city_zip = tx_city_zip.drop("73960")
need_columns = ["lat", "lng", "city", "county_name"]
tx_city_zip = tx_city_zip.loc[:, need_columns]
tx_city_zip = tx_city_zip.rename(columns={"lat": "Latitude", "lng": "Longitude", "city": "City", "county_name": "County"})
tx_city_zip

       Latitude  Longitude        City   County
zip
75001  32.96015  -96.83808     Addison   Dallas
75002  33.08946  -96.60639       Allen   Collin
75006  32.96165  -96.89717  Carrollton   Dallas
75007  33.00498  -96.89590  Carrollton   Denton
75009  33.33840  -96.75185      Celina   Collin
...         ...        ...         ...      ...
79932  31.87753 -106.60680     El Paso  El Paso
79934  31.95206 -106.43400     El Paso  El Paso
79935  31.76804 -106.33029     El Paso  El Paso
79936  31.77373 -106.29631     El Paso  El Paso
79938  31.85764 -106.03895     El Paso  El Paso

[1989 rows x 4 columns]

In [4]:
population_growth_df.index = population_growth_df.index.astype(str)
population_growth_df.index = population_growth_df.index.str.strip()

texas_population_growth = pd.merge(population_growth_df, tx_city_zip, left_index=True, right_index=True)
texas_population_growth = texas_population_growth[["City", "County", "Latitude", "Longitude", "2017", "2018", "2019", "2020", "2021", "2022"]]
texas_population_growth.index.name = "Zip"
texas_population_growth

,City,County,Latitude,Longitude,2017,2018,2019,2020,2021,2022
Zip,,,,,,,,,,
75001,Addison,Dallas,32.96015,-96.83808,14617,15000,14992,15418,16287,16633
75002,Allen,Collin,33.08946,-96.60639,69688,70597,71253,73916,71102,72679
75006,Carrollton,Dallas,32.96165,-96.89717,50788,51136,51642,52231,48104,48062
75007,Carrollton,Denton,33.00498,-96.89590,53744,54701,55500,57513,54448,54498
75009,Celina,Collin,33.33840,-96.75185,10557,11941,14089,15348,24737,28109
...,...,...,...,...,...,...,...,...,...,...
79932,El Paso,El Paso,31.87753,-106.60680,28345,28682,28243,28893,28594,29269
79934,El Paso,El Paso,31.95206,-106.43400,25846,26289,26445,26360,26916,26620
79935,El Paso,El Paso,31.76804,-106.33029,18166,17434,17850,18546,19073,18815
79936,El Paso,El Paso,31.77373,-106.29631,111918,112355,111620,108668,107579,107512
79938,El Paso,El Paso,31.85764,-106.03895,77487,80143,84237,83326,91575,95452

In [5]:
# texas_population_growth = texas_population_growth.set_index(["County", "Latitude", "Longitude", "City"], append=True)
# texas_population_growth

In [19]:
texas_population_growth.columns.get_loc("2018")

5

In [13]:
year_columns = texas_population_growth.columns[4:]
year_columns

Index(['2017', '2018', '2019', '2020', '2021', '2022'], dtype='object')

In [14]:
texas_population_growth[year_columns] = texas_population_growth[year_columns].apply(pd.to_numeric, errors= 'coerce')
percent_growth = pd.DataFrame(index = texas_population_growth.index)
original_year = 0
for year in range(original_year, len(texas_population_growth.columns) - 1):
    current_year = year + 1
    current_column = texas_population_growth.columns[current_year]
    percent_change = ((texas_population_growth[current_column] - texas_population_growth.iloc[:, year]) / texas_population_growth.iloc[:, year]) * 100
    percent_growth[current_column] = percent_change.map("{:.2f}%".format)

pd.reset_option('display.max_rows', None)
#percent_growth.dropna()
percent_growth.replace("nan%", "0.00%", inplace = True)
percent_growth

,County,Latitude,Longitude,2017,2018,2019,2020,2021,2022
Zip,,,,,,,,,
75001,0.00%,0.00%,-393.80%,-15194.27%,2.62%,-0.05%,2.84%,5.64%,2.12%
75002,0.00%,0.00%,-391.96%,-72236.02%,1.30%,0.93%,3.74%,-3.81%,2.22%
75006,0.00%,0.00%,-393.97%,-52514.33%,0.69%,0.99%,1.14%,-7.90%,-0.09%
75007,0.00%,0.00%,-393.58%,-55565.71%,1.78%,1.46%,3.63%,-5.33%,0.09%
75009,0.00%,0.00%,-390.21%,-11011.42%,13.11%,17.99%,8.94%,61.17%,13.63%
...,...,...,...,...,...,...,...,...,...
79932,0.00%,0.00%,-434.43%,-26688.36%,1.19%,-1.53%,2.30%,-1.03%,2.36%
79934,0.00%,0.00%,-433.11%,-24383.59%,1.71%,0.59%,-0.32%,2.11%,-1.10%
79935,0.00%,0.00%,-434.71%,-17184.50%,-4.03%,2.39%,3.90%,2.84%,-1.35%
79936,0.00%,0.00%,-434.54%,-105388.70%,0.39%,-0.65%,-2.64%,-1.00%,-0.06%
79938,0.00%,0.00%,-432.85%,-73174.09%,3.43%,5.11%,-1.08%,9.90%,4.23%

In [15]:
cleaned_percent = percent_growth[percent_growth.apply(lambda row: not row.isin(["inf%", "-inf%"]).any(), axis=1)]

pd.reset_option('display.max_rows', None)
cleaned_percent

,County,Latitude,Longitude,2017,2018,2019,2020,2021,2022
Zip,,,,,,,,,
75001,0.00%,0.00%,-393.80%,-15194.27%,2.62%,-0.05%,2.84%,5.64%,2.12%
75002,0.00%,0.00%,-391.96%,-72236.02%,1.30%,0.93%,3.74%,-3.81%,2.22%
75006,0.00%,0.00%,-393.97%,-52514.33%,0.69%,0.99%,1.14%,-7.90%,-0.09%
75007,0.00%,0.00%,-393.58%,-55565.71%,1.78%,1.46%,3.63%,-5.33%,0.09%
75009,0.00%,0.00%,-390.21%,-11011.42%,13.11%,17.99%,8.94%,61.17%,13.63%
...,...,...,...,...,...,...,...,...,...
79932,0.00%,0.00%,-434.43%,-26688.36%,1.19%,-1.53%,2.30%,-1.03%,2.36%
79934,0.00%,0.00%,-433.11%,-24383.59%,1.71%,0.59%,-0.32%,2.11%,-1.10%
79935,0.00%,0.00%,-434.71%,-17184.50%,-4.03%,2.39%,3.90%,2.84%,-1.35%
79936,0.00%,0.00%,-434.54%,-105388.70%,0.39%,-0.65%,-2.64%,-1.00%,-0.06%
79938,0.00%,0.00%,-432.85%,-73174.09%,3.43%,5.11%,-1.08%,9.90%,4.23%

In [16]:
cleaned_percent.shape

(1911, 9)

In [17]:
top_percentages = cleaned_percent.sort_values("2022", ascending = False)
top_twentyfive = top_percentages.head(25)
top_twentyfive

,County,Latitude,Longitude,2017,2018,2019,2020,2021,2022
Zip,,,,,,,,,
76519,0.00%,0.00%,-413.12%,-570.96%,-12.25%,21.45%,-28.13%,-28.57%,93.20%
79766,0.00%,0.00%,-422.80%,-6468.58%,4.54%,12.90%,-0.23%,40.11%,9.92%
75414,0.00%,0.00%,-386.79%,-3401.81%,-9.58%,18.65%,-0.64%,-11.93%,9.87%
77304,0.00%,0.00%,-414.91%,-30139.14%,7.29%,8.38%,7.58%,2.25%,9.86%
76853,0.00%,0.00%,-414.87%,-1700.76%,-1.97%,-5.70%,-8.45%,11.93%,9.85%
77564,0.00%,0.00%,-413.26%,-2198.04%,-15.51%,12.51%,-18.86%,13.38%,9.79%
76377,0.00%,0.00%,-388.86%,-934.67%,-3.29%,-30.01%,-25.23%,-3.86%,9.77%
75438,0.00%,0.00%,-385.88%,-1055.51%,-1.09%,9.25%,-1.92%,-2.06%,9.76%
79119,0.00%,0.00%,-390.58%,-15669.55%,3.21%,6.89%,5.63%,10.14%,9.73%
78950,0.00%,0.00%,-422.61%,-2172.86%,-10.75%,1.40%,2.93%,16.26%,9.70%
75082,0.00%,0.00%,-393.00%,-24651.71%,-0.65%,-0.41%,-0.28%,14.45%,9.65%
78949,0.00%,0.00%,-425.37%,-891.10%,-13.28%,-11.41%,39.32%,-26.52%,9.60%
76055,0.00%,0.00%,-402.08%,-2820.59%,2.27%,4.00%,13.16%,2.33%,9.55%
78880,0.00%,0.00%,-434.65%,-1927.92%,-1.15%,-10.26%,6.77%,-33.24%,9.49%
75709,0.00%,0.00%,-395.20%,-5389.92%,-0.83%,-5.46%,-2.26%,-0.61%,9.46%
78626,0.00%,0.00%,-418.26%,-33429.31%,3.37%,8.71%,5.42%,-3.38%,9.46%
75202,0.00%,0.00%,-395.33%,-2195.99%,1.48%,12.29%,18.47%,-19.24%,9.45%
76050,0.00%,0.00%,-401.07%,-6014.79%,8.60%,-0.46%,-1.90%,10.93%,9.39%
75451,0.00%,0.00%,-388.57%,-1149.22%,13.73%,2.47%,18.23%,7.27%,9.36%
76102,0.00%,0.00%,-397.11%,-10172.07%,-3.94%,-1.43%,14.54%,0.17%,9.34%
79407,0.00%,0.00%,-404.15%,-20697.72%,4.93%,3.36%,-2.85%,-4.27%,9.27%
78724,0.00%,0.00%,-422.22%,-25539.90%,-0.22%,3.81%,-1.54%,2.40%,9.23%
77554,0.00%,0.00%,-424.73%,-8789.98%,6.30%,-2.43%,2.03%,3.10%,9.15%
75054,0.00%,0.00%,-397.65%,-11193.01%,-1.20%,12.15%,9.37%,21.27%,9.11%
78545,0.00%,0.00%,-472.83%,-625.53%,9.79%,-29.72%,-49.75%,101.49%,9.09%

In [18]:
bottom_percentages = cleaned_percent.sort_values("2022", ascending = False)
bottom_twentyfive = bottom_percentages.tail(25)
bottom_twentyfive

,County,Latitude,Longitude,2017,2018,2019,2020,2021,2022
Zip,,,,,,,,,
76092,0.00%,0.00%,-394.79%,-31122.52%,2.55%,1.67%,1.31%,-1.76%,-0.20%
76116,0.00%,0.00%,-397.81%,-51193.07%,1.71%,-0.26%,-0.27%,-2.09%,-0.18%
76528,0.00%,0.00%,-411.06%,-17186.57%,0.70%,2.73%,11.22%,0.68%,-0.17%
78644,0.00%,0.00%,-426.98%,-18822.69%,-0.07%,0.63%,-3.89%,13.83%,-0.15%
77611,0.00%,0.00%,-412.61%,-8973.17%,3.70%,-0.64%,0.35%,14.18%,-0.15%
75227,0.00%,0.00%,-395.05%,-59885.92%,2.06%,1.57%,1.18%,-3.69%,-0.14%
79761,0.00%,0.00%,-421.28%,-33243.62%,0.11%,-1.05%,1.05%,-7.04%,-0.14%
77064,0.00%,0.00%,-419.31%,-51988.76%,0.43%,-2.32%,0.83%,0.54%,-0.13%
76801,0.00%,0.00%,-411.94%,-25255.82%,1.61%,-1.22%,-1.50%,1.81%,-0.13%
79005,0.00%,0.00%,-376.21%,-1744.67%,-0.85%,4.58%,-6.07%,3.79%,-0.12%
75229,0.00%,0.00%,-394.48%,-33538.23%,-1.85%,1.67%,1.29%,0.57%,-0.12%
77808,0.00%,0.00%,-412.81%,-11364.24%,10.07%,0.60%,1.96%,19.89%,-0.12%
78645,0.00%,0.00%,-421.74%,-11026.89%,5.13%,2.89%,2.54%,20.95%,-0.11%
78578,0.00%,0.00%,-473.50%,-12151.17%,-0.43%,0.81%,-2.23%,-8.32%,-0.10%
77070,0.00%,0.00%,-418.81%,-53545.63%,4.23%,-0.34%,6.04%,3.91%,-0.09%
75006,0.00%,0.00%,-393.97%,-52514.33%,0.69%,0.99%,1.14%,-7.90%,-0.09%
78550,0.00%,0.00%,-471.99%,-54107.58%,-1.00%,0.82%,-1.18%,4.74%,-0.08%
75251,0.00%,0.00%,-393.97%,-2546.96%,1.94%,18.52%,31.07%,1.44%,-0.08%
78357,0.00%,0.00%,-452.86%,-3054.46%,-1.55%,0.66%,-6.62%,4.60%,-0.07%
75847,0.00%,0.00%,-403.44%,-1974.17%,4.09%,-0.70%,-5.32%,-6.30%,-0.06%
76834,0.00%,0.00%,-412.02%,-5477.59%,-0.39%,-0.34%,1.13%,-6.98%,-0.06%
78045,0.00%,0.00%,-458.08%,-65025.99%,1.97%,1.07%,1.94%,-0.37%,-0.06%
79936,0.00%,0.00%,-434.54%,-105388.70%,0.39%,-0.65%,-2.64%,-1.00%,-0.06%
75216,0.00%,0.00%,-395.87%,-54753.44%,2.37%,-1.52%,1.74%,1.58%,-0.04%
78852,0.00%,0.00%,-447.99%,-55803.30%,1.72%,0.56%,0.00%,-0.72%,-0.00%